version: '3.8'

services:
  log-service:
    build:
      context: ./microservices/golang-services/log-service
      dockerfile: Dockerfile
    ports:
      - "8085:8083"  
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=logs_db
      - MONGO_COLLECTION=user_logs
      - PORT=8083
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
